packages:
  - "src/**"

allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
  svelte-preprocess: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - esbuild
  - prisma
  - svelte-preprocess
